version: "3"
services: 
    api:
        build: .
        #start up the service before this service.
        depends_on:
            - postgres
        ports:
            #<port on localhost>:<port on container>
            - 80: 8000
        #save the changes from the develop folder into the container folder    
        # volumes:
        #     - ./:/usr/src/app:ro # ro: read-on mode for security
        #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        # env_file:
        #     - ./.env
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=Zmj413902:)
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=60
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=Zmj413902:)
            - POSTGRES_DB=fastapi
            - 

        volumes:
            - postgres-db:/var/lib/postgressql/data

volumes:
    postgres-db: