"""add something

Revision ID: 21fdfc4f8431
Revises: fbffb7d1042a
Create Date: 2022-02-07 17:27:56.577495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fdfc4f8431'
down_revision = 'fbffb7d1042a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('something', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'something')
    # ### end Alembic commands ###
