"""add phone number

Revision ID: fbffb7d1042a
Revises: 4a79dcf60ff8
Create Date: 2022-02-07 17:22:52.999253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbffb7d1042a'
down_revision = '4a79dcf60ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    pass
    # ### end Alembic commands ###
