name: Build and Deploy Code

on: [push, pull_request]
  # push:
  #   branches: ["main"]
  #     #- "main"
  #     #- "anotherbranch"
  # pull_request:
  #   branches:
  #     -"test_branch"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to jordan
        run: echo "hello jordan"