name: Build and Deploy Code

on: [push, pull_request]

job:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to jordan
        run: echo "hello jordan"